#

---
- hosts: local
  connection: local
  vars:
    local_swap:  "{{ lookup('env','SWAPFILE') }}"
  tasks:
    - shell: lsblk -ln | grep "^sd[[:alpha:]].*disk" | awk '{ print $1 }'
      register: drives
    - shell: echo "no drives detected. Abort"
      when: "{{ drives.stdout_lines|length == 0}}"
    - meta: end_play
      when: "{{ drives.stdout_lines|length == 0}}"
    - command: "{{ item.1 }}"
      with_nested:
        - "{{ drives.stdout_lines }}"
        - [ 'local type=""', 'smartctl -d test /dev/{{ item.0 }} &>/dev/null || { smartctl -d sat -i /dev/{{ item.0 }} $>/dev/null || { echo "couldnt detect device type"; return 1; } type="-d sat" }', 'smartctl --smart=on /dev/{{ item.0 }} | sed 1,2d', if [[ "$SHORTTEST" == yes ]]; then { echo "* Starting test on $dr. Check results later" && smartctl $type -X "/dev/{{item.0}}" &>/dev/null && smartctl $type -t short "/dev/{{item.0}}" | sed 1,2d } elif [[ "$LONGTEST" == yes ]]; then {echo "* Starting test on {{item.0}}. Check results later" && smartctl $type -X "/dev/{{item.0}}" &>/dev/null && smartctl $type -t long "/dev/{{item.0}}" | sed 1,2d } else {echo "* Stats for {{ item.0 }}" && smartctl $type -a "/dev/{{ item.0 }}" | sed 1,2d } fi'
 ]

