#

---
- hosts: local
  connection: local
  vars:
    local_swap:  "{{ lookup('env','SWAPFILE') }}"
  tasks:
    - shell: lsblk -ln | grep "^sd[[:alpha:]].*disk" | awk '{ print $1 }'
      register: drives
    - shell: echo "no drives detected. Abort"
      when: "{{ drives.stdout_lines|length == 0}}"
    - meta: end_play
      when: "{{ drives.stdout_lines|length == 0}}"
    - command: {{ item.1 }}
      with_nested:
        - "{{ drives.stdout_lines }}"
        - [ 'local type=""', 'smartctl -d test /dev/{{ item.0 }} &>/dev/null || { smartctl -d sat -i /dev/{{ item.0 }} $>/dev/null || { echo "couldnt detect device type"; return 1; } type="-d sat" }', 'smartctl --smart=on /dev/{{ item.0 }}' ]

