#

---
- hosts: local
  connection: local
  vars:
    local_dockerbuild: "{{ dockerbuild }}"
  tasks:
    - apt:
        update_cache: yes
    - apt:
        force: yes
        install_recommends: no
        name: smartmontools
    - systemd:
      name: smartd
      enabled: no
      status: stopped
      when: local_dockerbuild != "1"
