#

---
- hosts: local
  connection: local
  vars:
    max_file_size:  "{{ maxfilesize }}"
    memory_limit: "{{ memorylimit }}"
    phpthreads: "{{ phpthreads }}"
    redis_mem: "{{ redismem }}"
  tasks:
    - shell: source /usr/local/etc/library.sh && echo "${PHPVER}"
      register: phpver
     
    - set_fact:
        phpver: "{{ phpver.stdout }}"

      # Set auto memory limit to 75% of the total memory
    - shell: free -b | sed -n 2p | awk '{ print $2 }'
      register: total_mem

    - shell: echo "$(( {{ total_mem.stdout }} * 75 / 100 ))"
      register: automem

    - set_fact:
        automem: "{{ automem.stdout }}"

      # MAX FILESIZE
    - shell: echo "/etc/php/{{ phpver }}/fpm/conf.d/90-ncp.ini"
      register: conf

    - shell: grep "^upload_max_filesize" "{{ conf.stdout }}" | sed 's|.*=||'
      register: current_file_size

    - set_fact:
        max_file_size: "10G"
      when: max_file_size == "0"

     # MAX PHP MEMORY
   - shell: echo "/etc/php/{{ phpver }}/fpm/conf.d/90-ncp.ini"
     register: conf

   - shell: grep "^memory_limit" "{{ conf.stdout }}" | sed 's|.*=||'
     register: current_php_mem

   - debug:
       msg: "Using {{ automem.stdout }}B for PHP"
     when: memory_limit == "0"
   
   - set_fact:
       memory_limit: "{{ automem }}"
     when: memory_limit == "0"

   - shell: sed -i "s/^post_max_size=.*/post_max_size={{ max_file_size }}/"             "{{ conf.stdout }}"

   - shell: sed -i "s/^upload_max_filesize=.*/upload_max_filesize={{ max_file_size }}/" "{{ conf.stdout }}"

   - shell: sed -i "s/^memory_limit=.*/memory_limit={{ memory_limit }}/"               "{{ conf.stdout }}"

     # MAX PHP THREADS
   - shell: echo "/etc/php/{{ phpver.stdout }}/fpm/pool.d/www.conf"
     register: conf

   - shell: grep "^pm.max_children" "{{ conf.stdout }}" | awk '{ print $3 }'
     register: current_threads

   - shell: nproc
     register: nproc
     when: phpthreads == "0"
    
   - set_fact:
      phpthreads: "{{ nproc.stdout }}"
     when: phpthreads == "0"

  - set_fact:
      phpthreads: "3"
    when: phpthreads < "3"

  - debug:
      msg: "Using {{ phpthreads }} PHP threads"

  - shell: sed -i "s|^pm =.*|pm = static|"                                "{{ conf.stdout }}"
    
  - shell: sed -i "s|^pm.max_children =.*|pm.max_children = {{ phpthreads }}|" "{{ conf.stdout }}"

    # DATABASE MEMORY
  - shell: echo "$(( {{ total_mem.stdout }} * 40 / 100 ))"
      register: automem

  - set_fact:
      automem: "{{ automem.stdout }}"

  - shell: echo "/etc/mysql/mariadb.conf.d/91-ncp.cnf"
    register: conf

  - shell: grep "^innodb_buffer_pool_size" "{{ conf.stdout }}" | awk '{ print $3 }'
    register: current_db_mem

  - debug:
      msg: "Using {{ automem }} memory for database"

  - shell: sed -i "s|^innodb_buffer_pool_size =.*|innodb_buffer_pool_size = {{ automem }}|" "{{ conf.stdout }}"
    when: current_db_mem.stdout != automem

  - systemd:
      name: mysql
      state: restarted
    when: current_db_mem.stdout != automem

    # RESTART PHP
  - shell: bash -c "sleep 3; service php${PHPVER}-fpm restart" &>/dev/null &
    when: (not phpthreads != current_threads.stdout) and (not memorylimit != current_php_mem.stdout) and (max_file_size != current_file_size.stdout)

    # redis max memory
    
  - shell: echo "/etc/redis/redis.conf"
    register: conf

  - shell: grep "^maxmemory" "$CONF" | awk '{ print $2 }'
    register: current_redis_mem

  - shell: sed -i "s|^maxmemory .*|maxmemory {{ redis_mem }}|" "{{ conf.stdout }}"
    when: redis_mem != current_redis_mem.stdout

  - systemd:
      name: redis-server
      state: restarted
    when: redis_mem != current_redis_mem.stdout

