#

---
- hosts: local
  connection: local
  vars:
    active: "{{ lookup('env','ACTIVE') }}"
    user: "{{ lookup('env', 'USER') }}"
    confirm: "{{ lookup('env', 'CONFIRM') }}"
  tasks:
    - shell: echo "Off"
      register: opt
      when: active == "no"

    - shell: echo "On"
      register: opt
      when: active != "no"

    - shell: sed -i "s|RewriteEngine .*|RewriteEngine {{ opt.stdout }}|" /etc/apache2/sites-available/000-default.conf

    - debug:
        msg: "Forcing HTTPS {{ opt.stdout }}"
        
    - shell: bash -c "sleep 2 && service apache2 reload" &>/dev/null &
