stages:
        - building
sudo: required
language: generic
dist: xenial
branches:
  only:
        - gsoc2019-travis
jobs:
  include:
        - stage: building

          install:
          - sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
         
          script:
          - vagrant up
          - curl -sSL https://raw.githubusercontent.com/nextcloud/nextcloudpi/master/install.sh | bash

notifications:
  email: false
