# -*- mode: ruby -*-
# vi: set ft=ruby :

#
# Vagrantfile for the NCP Debian VM
#
# Instructions: vagrant up; vagrant ssh
#
# Notes: User/Pass is ubnt/ubnt.
# $HOME is accessible as /external. CWD is accessible as /cwd
#

Vagrant.configure("2") do |config|

  vmname = "workerX-NCP"

  #Box settings
  config.vm.box = "debian/stretch64"
  config.vm.box_check_update = false

  #VM settings
  config.vm.hostname = "workerX-ncp-vm"

  #Networking

  #Public IP
  config.vm.network "public_network", bridge: "wlp4s0", ip: "192.168.1.21"

  #Provider settings
  config.vm.provider "virtualbox" do |v|
    #Resources
    v.memory = 4096
    v.cpus = 4

    #VM name
    v.name = "workerX-NextCloudPi"

  end


  config.vm.synced_folder '.', '/vagrant'

  $script = <<-SHELL
    sudo su
    BRANCH=master
    #BRANCH=gsoc2019-devel  # uncomment to install devel
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends git

    # Install docker
    curl -fsSL https://get.docker.com -o get-docker.sh
    sudo sh get-docker.sh
    echo $'{
      "experimental": true,
      "storage-driver": "overlay2"
    }' | sudo tee /etc/docker/daemon.json
    sudo service docker restart


    # indicate that this will be an image build
    touch /.ncp-image

    # install from the official repo
    git clone -b "$BRANCH" https://github.com/nextcloud/nextcloudpi.git /tmp/nextcloudpi
    cd /tmp/nextcloudpi

    # uncomment to install devel
    #sed -i 's|^BRANCH=gsoc2019-master|BRANCH=gsoc2019-devel|' install.sh ncp.sh

    #Do alltogether so that the install.sh won't fail as it does sometimes when run alone
    bash install.sh && source etc/library.sh && run_app_unsafe post-inst.sh && cd - && systemctl disable sshd && poweroff

    # cleanup
#    source etc/library.sh
#    run_app_unsafe post-inst.sh
#    cd -
#    rm -r /tmp/nextcloudpi
#    systemctl disable sshd
#    poweroff
  SHELL

  # Provision the VM
  config.vm.provision "shell", inline: $script

end
