#

---
- hosts: local
  connection: local
  tasks:
    - shell: grep datadirectory /var/www/nextcloud/config/config.php | awk '{ print $3 }' | grep -oP "[^']*[^']" | head -1
      register: srcdir

    - meta: end_play
      when: srcdir.stdout != "/var/www/nextcloud/data"
