#

---
- hosts: local
  connection: local
  tasks:
    - name: existence of /var/log.hdd
      stat:
        path: /var/log.hdd
      register: log_hdd

    - name: existence of /var/hdd.log
      stat:
        path: /var/hdd.log
      register: hdd_log

    - name: one of the dirs exists
      debug:
        msg: "log2ram detected, not installing"
      when: (log_hdd.stat.exists and log_hdd.stat.isdir) or (hdd_log.stat.exists and hdd_log.stat.isdir)

    - meta: end_play
      when: (log_hdd.stat.exists and log_hdd.stat.isdir) or (hdd_log.stat.exists and hdd_log.stat.isdir)

    - command: chdir=/tmp curl -Lo log2ram.tar.gz https://github.com/azlux/log2ram/archive/master.tar.gz

    - unarchive:
        src: /tmp/log2ram.tar.gz
        dest: /tmp/

    - shell: sed -i '/systemctl -q is-active log2ram/d' /tmp/log2ram-master/install.sh

    - shell: sed -i '/systemctl enable log2ram/d' /tmp/log2ram-master/install.sh

    - file: dest=/tmp/log2ram-master/install.sh mode=+x

    - file:
        path: /tmp/log2ram-master
        state: absent

    - file:
        path: /tmp/log2ram.tar.gz
        state: absent

    - file:
        path: /etc/cron.hourly/log2ram
        state: absent

    - file:
        path: /usr/local/bin/uninstall-log2ram.sh
        state: absent
 
