#

---
- hosts: local
  connection: local
  vars:
    local_dbdir:  "{{ lookup('env','DBDIR') }}"
  tasks:

    - shell: grep datadir /etc/mysql/mariadb.conf.d/90-ncp.cnf | awk -F "= " '{ print $2 }'
      register: srcdir

    - stat:
        path: "{{ srcdir.stdout }}"
      register: folder_srcdir

    - shell: echo -e "database directory $SRCDIR not found"
      when: not (folder_srcdir.stat.exists and folder_srcdir.stat.isdir)

    - fail:
        msg: "database directory not found"
      when: not (folder_srcdir.stat.exists and folder_srcdir.stat.isdir)

    - stat:
        path: "{{ dbdir }}"
      register: folder_dbdir

    - shell: find "$DBDIR" -maxdepth 0 -empty | wc -l
      register: find_dbdir
      when: folder_dbdir.stat.exists and folder_dbdir.stat.isdir

    - shell: echo "Dbdir is not empty"
      when: folder_dbdir.stat.exists and folder_dbdir.stat.isdir and find_dbdir.stdout == "0"

    - fail:
        msg: "Dbdir is not empty"
      when: folder_dbdir.stat.exists and folder_dbdir.stat.isdir and find_dbdir.stdout == "0"

    - shell: ls | wc -l 
      register: isempty
      when: folder_dbdir.stat.exists and folder_dbdir.stat.isdir

    - file:
        path: "{{ dbdir }}"
        state: absent
      when: folder_dbdir.stat.exists and folder_dbdir.stat.isdir and isempty.stdout == "0"

    - shell: dirname {{ dbdir }}
      register: basedir

    - stat:
        path: "{{ basedir.stdout }}"
      register: basedir_results

    - file:
        path: "{{ basedir.stdout }}"
        state: directory
      when: not basedir_results.stat.exists

    - shell: grep -q -e ext -e btrfs <( stat -fc%T "$BASEDIR" )
      register: btrfs_basedir

    - fail:
        msg: "Only ext/btrfs filesystems can hold the data directory"
      when: brrfs_basedir.stdout == ""

    - shell: sudo -u mysql test -x "$BASEDIR"
      register: mysqltest

    - fail:
        msg: "ERROR: the user mysql does not have access permissions over $BASEDIR"
      when: mysqltest.stdout == ""

    - shell: [ $( stat -fc%d / ) == $( stat -fc%d "$BASEDIR" ) ]] && echo -e "INFO: moving database to the SD card\nIf you want to use an external mount, make sure it is properly set up"

    - command: chdir=/var/www/nextcloud sudo -u www-data php occ maintenance:mode --on
    - shell: echo "moving database to $DBDIR..."

    - systemd: 
      name: mysql
      status: stopped

    - shell: mv "$SRCDIR" "$DBDIR" && sed -i "s|^datadir.*|datadir = $DBDIR|" /etc/mysql/mariadb.conf.d/90-ncp.cnf

    - systemd: 
      name: mysql
      status: started

    - command: chdir=/var/www/nextcloud sudo -u www-data php occ maintenance:mode --ff

