#

---
- hosts: local
  connection: local
  vars:
    local_dbdir:  "{{ lookup('env','DBDIR') }}"
  tasks:

    - shell: grep datadir /etc/mysql/mariadb.conf.d/90-ncp.cnf | awk -F "= " '{ print $2 }'
      register: srcdir

    - stat:
        path: "{{ srcdir.stdout }}"
      register: folder_srcdir

    - shell: echo -e "database directory $SRCDIR not found"
      when: not (folder_srcdir.stat.exists and folder_srcdir.stat.isdir)

    - fail:
        msg: database directory not found
      when: not (folder_srcdir.stat.exists and folder_srcdir.stat.isdir)

    - stat:
        path: "{{ dbdir }}"
      register: folder_dbdir

      # TODO: find command here needs to be fixed

    - shell: echo "Dbdir is not empty"
      when: folder_dbdir.stat.exists and folder_dbdir.stat.isdir

















    - name: Stop and disable automount if active
      systemd: 
      name: nc-automount
      status: stopped
      enabled: no
      when: local_active != "yes"
    - name: Stop and disable automount-links if active
      systemd: 
      name: nc-automount-links
      status: stopped
      enabled: no
      when: local_active != "yes"
    - file:
        path: /etc/systemd/system/{mariadb,nfs-server,dphys-swapfile,fail2ban}.service.d
        state: absent
        force: yes
      when: local_active != "yes"
    - name: reload systemd
      sudo: yes
      command: systemctl daemon-reload
      when: local_active != "yes"
    - shell: echo "automount disabled"
      when: local_active != "yes"
    - meta: end_play
      when: local_active != "yes"

    - systemd: 
      name: nc-automount
      status: started
      enabled: yes
    - systemd: 
      name: nc-automount-links
      status: started
      enabled: yes

    - stat:
       path: "{{item}}"
      register: folder_stats
      with_items:
      - ["/etc/systemd/system/mariadb.service.d","etc/systemd/system/nfs-server.service.d","/etc/systemd/system/dphys-swapfile.service.d","/etc/systemd/system/fail2ban.service.d"]
    - name: "Creating multiple folders without disturbing previous permissions"
      file:
       path: "{{item.item}}"
       state: directory
      when: item.stat.exists == false
      with_items:
      - "{{folder_stats.results}}"

    - file:
        path: /etc/systemd/system/mariadb.service.d/ncp-delay-automount.conf
        state: touch
    - blockinfile:
        path: /etc/systemd/system/mariadb.service.d/ncp-delay-automount.conf
        block: |
          [Service]
          ExecStartPre=/bin/sleep 20
          Restart=on-failure
    - file:
        path: /etc/systemd/system/nfs-server.service.d/ncp-delay-automount.conf
        state: touch
    - blockinfile:
        path: /etc/systemd/system/nfs-server.service.d/ncp-delay-automount.conf
        block: |
          [Service]
          ExecStartPre=
          ExecStartPre=/bin/bash -c "/bin/sleep 30; /usr/sbin/exportfs -r"
    - file:
        path: /etc/systemd/system/dphys-swapfile.service.d/ncp-delay-automount.conf
        state: touch
    - blockinfile:
        path: /etc/systemd/system/dphys-swapfile.service.d/ncp-delay-automount.conf
        block: |
          [Service]
          ExecStartPre=/bin/sleep 30
    - file:
        path: /etc/systemd/system/fail2ban.service.d
        state: touch
    - blockinfile:
        path: /etc/systemd/system/fail2ban.service.d
        block: |
          [Service]
          ExecStartPre=/bin/sleep 10
    - name: reload systemd
      sudo: yes
      command: systemctl daemon-reload
    - shell: echo "automount enabled"
 
