#

---
- hosts: local
  connection: local
  tasks:
    - shell: grep datadir /etc/mysql/mariadb.conf.d/90-ncp.cnf | awk -F "= " '{ print $2 }'
      register: srcdir

    - meta: end_play
      when: srcdir.stdout != "/var/lib/mysql"

